# Generated by Django 5.2.5 on 2025-08-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('pdf_url', models.URLField(help_text='Direct link to the PDF certificate')),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, help_text='Brief description', max_length=500)),
                ('is_featured', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['display_order', '-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='DjangoCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Resume', max_length=100)),
                ('pdf_url', models.URLField(help_text='Direct link to the CV/Resume PDF')),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Currently active CV')),
                ('description', models.TextField(blank=True, max_length=300)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CV/Resume',
                'verbose_name_plural': 'CV/Resumes',
                'ordering': ['-upload_date'],
            },
        ),
    ]
