# Generated by Django 5.2.5 on 2025-08-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('image_url', models.URLField(blank=True, help_text='Direct link to project image')),
                ('technologies', models.CharField(help_text='Comma-separated list of technologies', max_length=500)),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository link')),
                ('live_url', models.URLField(blank=True, help_text='Live demo link')),
                ('is_featured', models.BooleanField(default=True, help_text='Show on portfolio')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_date'],
            },
        ),
    ]
